# Generated by Django 3.1.5 on 2021-01-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryWeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name_city', models.CharField(blank=True, max_length=50, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
